//first name, last name, email, password, address, city

const keyurData = [
    {
        users_ID: 420,
        first_name: "Keyur",
        last_name: "Mistry",
        phone_number: "07823420690",
        email: "awesome@gmail.com",
        password: "hellothere",
        address: "1 awesomeville road",
        city: "Birmingham",
    },
    {
        users_ID: 421,
        first_name: "Key",
        last_name: "Mist",
        phone_number: "07823420691",
        email: "awesome1@gmail.com",
        password: "hellothere",
        address: "2 awesomeville road",
        city: "Birmingham",
    },
    {
        users_ID: 440,
        first_name: "Keyu",
        last_name: "Mis",
        phone_number: "07823420692",
        email: "awesome2@gmail.com",
        password: "hellothere",
        address: "3 awesomeville road",
        city: "Birmingham",
    },
    {
        users_ID: 422,
        first_name: "Keruy",
        last_name: "Mister",
        phone_number: "07823420693",
        email: "awesome3@gmail.com",
        password: "hellothere",
        address: "4 awesomeville road",
        city: "Birmingham",
    },
    {
        users_ID: 423,
        first_name: "Keyura",
        last_name: "Mistries",
        phone_number: "07823420694",
        email: "awesome4@gmail.com",
        password: "hellothere",
        address: "5 awesomeville road",
        city: "Birmingham",
    },
    {
        users_ID: 424,
        first_name: "Steve",
        last_name: "Mistry",
        phone_number: "07823420695",
        email: "awesome5@gmail.com",
        password: "hellothere",
        address: "6 awesomeville road",
        city: "Birmingham",
    },
    {
        users_ID: 425,
        first_name: "Keyurin",
        last_name: "Mistrin",
        phone_number: "07823420696",
        email: "awesome6@gmail.com",
        password: "hellothere",
        address: "7 awesomeville road",
        city: "Birmingham",
    },
    {
        users_ID: 426,
        first_name: "Keyuro",
        last_name: "Mistron",
        phone_number: "07823420697",
        email: "awesome7@gmail.com",
        password: "hellothere",
        address: "8 awesomeville road",
        city: "Birmingham",
    },
    {
        users_ID: 427,
        first_name: "Keyurok",
        last_name: "Mistrint",
        phone_number: "07823420698",
        email: "awesome8@gmail.com",
        password: "hellothere",
        address: "9 awesomeville road",
        city: "Birmingham",
    },
    {
        users_ID: 428,
        first_name: "Natasha",
        last_name: "Beddow",
        phone_number: "07823420680",
        email: "exchange@gmail.com",
        password: "hellothere",
        address: "1 exchange road",
        city: "Manchester",
    },
    {
        users_ID: 429,
        first_name: "Nat",
        last_name: "Bedd",
        phone_number: "07823420681",
        email: "exchange1@gmail.com",
        password: "hellothere",
        address: "2 exchange road",
        city: "Manchester",
    },
    {
        users_ID: 430,
        first_name: "Ash",
        last_name: "Be",
        phone_number: "07823420682",
        email: "exchange2@gmail.com",
        password: "hellothere",
        address: "3 exchange road",
        city: "Manchester",
    },
    {
        users_ID: 431,
        first_name: "Asha",
        last_name: "Dow",
        phone_number: "07823420683",
        email: "exchange3@gmail.com",
        password: "hellothere",
        address: "4 exchange road",
        city: "Manchester",
    },
    {
        users_ID: 432,
        first_name: "Nash",
        last_name: "Bedo",
        phone_number: "07823420683",
        email: "exchange4@gmail.com",
        password: "hellothere",
        address: "5 exchange road",
        city: "Manchester",
    },
    {
        users_ID: 433,
        first_name: "Steve",
        last_name: "Bedew",
        phone_number: "07823420684",
        email: "exchange@gmail.com",
        password: "hellothere",
        address: "6 exchange road",
        city: "Manchester",
    },
    {
        users_ID: 434,
        first_name: "Nashin",
        last_name: "Beddin",
        phone_number: "07823420685",
        email: "exchange6@gmail.com",
        password: "hellothere",
        address: "7 exchange road",
        city: "Manchester",
    },
    {
        users_ID: 435,
        first_name: "Nasho",
        last_name: "Bedron",
        phone_number: "07823420686",
        email: "exchange7@gmail.com",
        password: "hellothere",
        address: "8 exchange road",
        city: "Manchester",
    },
    {
        users_ID: 436,
        first_name: "Nashok",
        last_name: "Beddin",
        phone_number: "07823420687",
        email: "exchange8@gmail.com",
        password: "hellothere",
        address: "9 exchange road",
        city: "Manchester",
    },
]

const propertyData = [
    {
        propertyID: 324,
        address: "1 wishful lane",
        city: "Birmingham",
        price: "£500",
        bathroom: 2,
        rooms: 4,
        reception: 1,
        description:"Beautiful exterior and close to public services",
        available: "yes",
    },
    {
        propertyID: 420,
        address: "2 wishful lane",
        city: "Birmingham",
        price: "£550",
        bathroom: 3,
        rooms: 5,
        reception: 1,
        description:"Comfortable interior witha a big garden",
        available: "yes",
    },
    {
        propertyID: 547,
        address: "3 wishful lane",
        city: "Birmingham",
        price: "£400",
        bathroom: 1,
        rooms: 3,
        reception: 1,
        description:"Cosy space for a small family",
        available: "yes",
    },
    {
        propertyID: 798,
        address: "4 wishful lane",
        city: "Birmingham",
        price: "£600",
        bathroom: 3,
        rooms: 5,
        reception: 2,
        description:"Luxurious space and well sized rooms",
        available: "yes",
    },
    {
        propertyID: 234,
        address: "5 wishful lane",
        city: "Birmingham",
        price: "£530",
        bathroom: 2,
        rooms: 5,
        reception: 1,
        description:"wide open spaces with a great view",
        available: "yes",
    },
    {
        propertyID: 542,
        address: "6 wishful lane",
        city: "Birmingham",
        price: "590",
        bathroom: 3,
        rooms: 6,
        reception: 2,
        description:"many well sized rooms fit for a big family",
        available: "yes",
    },
    {
        propertyID: 466,
        address: "7 wishful lane",
        city: "Birmingham",
        price: "£450",
        bathroom: 2,
        rooms: 3,
        reception: 2,
        description:"strong, vintage structure with a big garden",
        available: "yes",
    },
    {
        propertyID: 690,
        address: "8 wishful lane",
        city: "Birmingham",
        price: "£559",
        bathroom: 3,
        rooms: 4,
        reception: 2,
        description:"cosy living space with many well sized bathrooms",
        available: "yes",
    },
    {
        propertyID: 893,
        address: "9 wishful lane",
        city: "Birmingham",
        price: "£500",
        bathroom: 4,
        rooms: 7,
        reception: 2,
        description:"wide, open living space with great views and accessibility",
        available: "yes",
    },
]