//first name, last name, email, password, address, city

// const propertyData = [
//   {
//     address: '1 wishful lane',
//     city: 'Birmingham',
//     price: '£500',
//     bathroom: 2,
//     rooms: 4,
//     reception: 1,
//     description: 'Beautiful exterior and close to public services',
//     available: 'yes',
//   },
//   {
//     address: '2 wishful lane',
//     city: 'Birmingham',
//     price: '£550',
//     bathroom: 3,
//     rooms: 5,
//     reception: 1,
//     description: 'Comfortable interior witha a big garden',
//     available: 'yes',
//   },
//   {
//     address: '3 wishful lane',
//     city: 'Birmingham',
//     price: '£400',
//     bathroom: 1,
//     rooms: 3,
//     reception: 1,
//     description: 'Cosy space for a small family',
//     available: 'yes',
//   },
//   {
//     address: '4 wishful lane',
//     city: 'Birmingham',
//     price: '£600',
//     bathroom: 3,
//     rooms: 5,
//     reception: 2,
//     description: 'Luxurious space and well sized rooms',
//     available: 'yes',
//   },
//   {
//     address: '5 wishful lane',
//     city: 'Birmingham',
//     price: '£530',
//     bathroom: 2,
//     rooms: 5,
//     reception: 1,
//     description: 'wide open spaces with a great view',
//     available: 'yes',
//   },
//   {
//     address: '6 wishful lane',
//     city: 'Birmingham',
//     price: '590',
//     bathroom: 3,
//     rooms: 6,
//     reception: 2,
//     description: 'many well sized rooms fit for a big family',
//     available: 'yes',
//   },
//   {
//     address: '7 wishful lane',
//     city: 'Birmingham',
//     price: '£450',
//     bathroom: 2,
//     rooms: 3,
//     reception: 2,
//     description: 'strong, vintage structure with a big garden',
//     available: 'yes',
//   },
//   {
//     address: '8 wishful lane',
//     city: 'Birmingham',
//     price: '£559',
//     bathroom: 3,
//     rooms: 4,
//     reception: 2,
//     description: 'cosy living space with many well sized bathrooms',
//     available: 'yes',
//   },
//   {
//     address: '9 wishful lane',
//     city: 'Birmingham',
//     price: '£500',
//     bathroom: 4,
//     rooms: 7,
//     reception: 2,
//     description: 'wide, open living space with great views and accessibility',
//     available: 'yes',
//   },
// ];

// const bookingData = [
//     {
//         property_id: 1,
//         user_id: 1,
//         starting_date: ,
//     },
// ]
